kind: pipeline
type: docker
name: default

steps:
  - name: my_ip
    image: curlimages/curl:7.69.1
    commands:
      - curl httpbin.org/ip

  - name: copy_kubernetest_manifest
    image: appleboy/drone-scp
    settings:
      host: ec2-18-191-221-199.us-east-2.compute.amazonaws.com
      port: 22
      username: ec2-user
      key:
        from_secret: SSH_PRIVATE_KEY
      source:
        - ./manifest/valaxy-deploy.yml
        - ./manifest/valaxy-service.yml
      target: /tmp

  - name: apply_kubernetes_manifest
    image: appleboy/drone-ssh
    settings:
      host: ec2-18-191-221-199.us-east-2.compute.amazonaws.com
      port: 22 
      username: ec2-user
      key:
        from_secret: SSH_PRIVATE_KEY
      script:
        - kubectl apply -f /tmp/valaxy-deploy.yml
        - kubectl apply -f /tmp/valaxy-service.yml
